services:
  php:
    volumes:
      - unix-socks:/var/run
      - /home/ilias.almerekov/Projects/Backend/backend/app:/var/www/html

  nginx:
    volumes:
      - ./etc/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /home/ilias.almerekov/Projects/Backend/backend/app:/var/www/html
      - unix-socks:/var/run
