# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    frontend_url: "%env(string:FRONTEND_URL)%"

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: "../src/"

    App\Repository\RoundRepositoryInterface: '@App\Repository\RoundRepository'
    App\Repository\RoundThrowsRepositoryInterface: '@App\Repository\RoundThrowsRepository'
    App\Repository\GamePlayersRepositoryInterface: '@App\Repository\GamePlayersRepository'
    App\Repository\GameRepositoryInterface: '@App\Repository\GameRepository'
    App\Repository\InvitationRepositoryInterface: '@App\Repository\InvitationRepository'
    App\Repository\PlayerStatsRepositoryInterface: '@App\Repository\PlayerStatsRepository'
    App\Repository\UserRepositoryInterface: '@App\Repository\UserRepository'
    App\Service\Invitation\InvitationServiceInterface: '@App\Service\Invitation\InvitationService'
    App\Service\Registration\RegistrationServiceInterface: '@App\Service\Registration\RegistrationService'
    App\Service\Security\SecurityServiceInterface: '@App\Service\Security\SecurityService'
    App\Service\Security\GameAccessServiceInterface: '@App\Service\Security\GameAccessService'
    App\Service\Game\GameStartServiceInterface: '@App\Service\Game\GameStartService'
    App\Service\Game\GameSettingsServiceInterface: '@App\Service\Game\GameSettingsService'
    App\Service\Game\GameRoomServiceInterface: '@App\Service\Game\GameRoomService'
    App\Service\Game\GameThrowServiceInterface: '@App\Service\Game\GameThrowService'
    App\Service\Game\GameServiceInterface: '@App\Service\Game\GameService'
    App\Service\Game\GameStatisticsServiceInterface: '@App\Service\Game\GameStatisticsService'
    App\Service\Game\GameFinishServiceInterface: '@App\Service\Game\GameFinishService'
    App\Service\Game\GameAbortServiceInterface: '@App\Service\Game\GameAbortService'
    App\Service\Game\RematchServiceInterface: '@App\Service\Game\RematchService'
    App\Service\Player\PlayerManagementServiceInterface: '@App\Service\Player\PlayerManagementService'
    App\Service\Sse\SseStreamServiceInterface: '@App\Service\Sse\SseStreamService'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
